baseURL = "/"
languageCode = "en-us"
title = "Grem1in's Blog"
theme = "tracks"
disqusShortname = "grem1in"
googleAnalytics = ""

[params]
  style = "default"
  pages = false
  description = "Yurii's Blog"
  copyright = "&copy;2019 Yurii Rochniak"
  sidebarAbout = [
    "I am an SRE with the Cloud experience. Passionate about the CICD related things."
    "Originally from Kyiv, currently based in Berlin."
  ]

  email = "yrochnyak@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  telegram      = "https://t.me/catops"
  email         = "yrochnyak@gmail.com"
  twitter       = "https://twitter.com/grem11n"
  linkedin      = "https://www.linkedin.com/in/yrochnyak/"
  stackoverflow = "https://stackoverflow.com/users/6099033/yurii-rochniak?tab=profile"
  github        = "https://github.com/grem11n"
