baseURL = "/"
languageCode = "en-us"
title = "YR's Blog"
theme = "hugo-gentoo-theme"
disqusShortname = "grem1in"
googleAnalytics = "UA-142478515-1"

copyright = "(c) 2017 Yurii's Rochniak Blog"
canonifyurls = true
paginate = 6
enableInlineShortcodes = true
enableEmoji = true

[params]
  author = "Yurii Rochniak"
  description = "Site Reliability Engineer. Write a bit about life and tech. Opinions on my own"
  mainSections = ["post", "posts"]
  images = ["/img/card_iamge.jpg"]

[taxonomies]
  category = "categories"
  tag = "tags"


[[menu.global]]
    name = "About"
    url = "/about/"

[[menu.global]]
    name = "Talks"
    url = "/talks/"

[params.social]
    twitter       = "grem11n"
    github        = "grem11n"
    telegram      = "catops"
    goodreads     = "9974285-yura"
    email         = "yrochnyak@gmail.com"
    linkedin      = "yrochnyak/"
    stackoverflow = "6099033/yurii-rochniak?tab=profile"
