baseURL = "/"
languageCode = "en-us"
title = "YR's Blog"
theme = "gentoo"
disqusShortname = "grem1in"
googleAnalytics = "UA-142478515-1"

copyright = "(c) 2017 Yurii's Rochniak Blog"
canonifyurls = true
paginate = 6

[params]
  description = "Personal Blog. Opinions on my own."
  author = "Yurii Rochniak"

[taxonomies]
  category = "categories"
  tag = "tags"


[[menu.global]]
    name = "Contact"
    url = "/contact/"

[[menu.global]]
    name = "About"
    url = "/about/"

[params.social]
    twitter       = "grem11n"
    github        = "grem11n"
    telegram      = "catops"
    email         = "yrochnyak@gmail.com"
    linkedin      = "yrochnyak/"
    stackoverflow = "6099033/yurii-rochniak?tab=profile"
